// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID   int32       `json:"id"`
	Name string      `json:"name"`
	Dob  pgtype.Date `json:"dob"`
}
